[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8 --no-location"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
